services:

  webapp:
    container_name: "peppux-php"
    environment:
      - ENV=local
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "${DOCKER_CONTAINER_PORT:-80}:80"
    volumes:
      - ./src/:/var/www
    networks:
      - network

  mysql:
    image: mysql:8.4.4
    container_name: "peppux-mysql"
    restart: on-failure
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - database_volume:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - network

#Docker Networks
networks:
  network:
    driver: bridge
    name: "peppux-network"

#Volumes
volumes:
  database_volume:
    name: "peppux-mysql"
    driver: local
