version: '3'
services:

  webapp:
    container_name: "${DOCKER_CONTAINER_NAME:-api}-php"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        COMPOSER_ALLOW_SUPERUSER: 1
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
    networks:
      - network

  nginx:
    image: nginx:alpine
    container_name: "${DOCKER_CONTAINER_NAME:-api}-nginx"
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_CONTAINER_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - network

  mysql:
    image: mysql/mysql-server:8.0.23
    container_name: "${DOCKER_CONTAINER_NAME:-api}-mysql"
    restart: unless-stopped
    tty: true
    command:
      - --explicit_defaults_for_timestamp
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - volume_db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - network

#Docker Networks
networks:
  network:
    driver: bridge
    name: "${DOCKER_CONTAINER_NAME:-api}-network"

#Volumes
volumes:
  volume_db:
    name: "${DOCKER_CONTAINER_NAME:-api}-mysql"
    driver: local
